### PR TITLE
Fix postcss and Add component

### PR DESCRIPTION
**Pull request by bgsrb**
Fix postcss plugin and clean project
Add button signup component

### CODE REVIEW

**Comment by ErFUN-KH** [comment]
Hi @bgsrb 

Thank you for the PR, but I found 2 issues:
1- don't add `public/build/` to .gitignore
2- there is some conflict

After you fix those issues we can merge the PR.

**Comment by bgsrb** [comment]
Why shouldn't this folder be ignored?
This will increase the size of the project with each change of source and build it.

**Comment by bgsrb** [comment]
This branch has no conflicts with the base branch

**Comment by ErFUN-KH** [comment]
> Why shouldn't this folder be ignored?
> This will increase the size of the project with each change of source and build it.

because it's just a template, I just want to open HTML and check files, we will ignore that in another repository.

**Pull request merged**
